import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidebarMenu from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="border-b">
          <div className="flex h-16 items-center px-4 container">
            Hello
              <div className="ml-auto flex items-center space-x-4">
                
              </div>
          </div>
        </div> 
        <div className="flex">
           
          <SidebarMenu/>
          <div className="w-full px-4 pt-12">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
